BikeSharing/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from bikeShare import views as bikeShareViews

"""General patterns"""
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='registration/home.html'), name='home'),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^logout', auth_views.logout, name='logout'),
    url(r'^register', bikeShareViews.register, name='register'),
    url(r'^share/', include('bikeShare.urls')),
    url(r'^change_password/', bikeShareViews.change_password, name='changePassword'),
    url(r'^admin/', admin.site.urls, name='adminSite'),
]

bikeShare/urls.py
from django.conf.urls import url
from bikeShare import views

app_name = 'bikeShare'
urlpatterns = [
    # home view ex
    url(r'^$', views.home_view, name='Home'),
    # list of stations
    url(r'^stations$', views.StationsListView.as_view(), name='Stations'),
    # specific station
    url(r'^stations/(?P<station_id>[0-9]+)$', views.bikes_view, name='StationIndex'),
    # list of bikes to borrow
    url(r'^stations/(?P<station_id>[0-9]+)/borrow$', views.borrow_bike, name='Borrow'),
    # specific ride
    url(r'^rides/(?P<ride_id>[0-9]+$)', views.ride_view, name="RideIndex"),
    # all rides of a user
    url(r'^rides$', views.rides_view, name="Rides"),
    # choose station to finish ride at
    url(r'^rides/(?P<ride_id>[0-9]+)/finish$', views.finish_ride_select_station, name="FinishRideSelectStation"),
    # finish ride at selected station
    url(r'^rides/(?P<ride_id>[0-9]+)/finish/(?P<station_id>[0-9]+)$', views.finish_ride_at_station,
        name="FinishRideAtStation"),
    # report bike as broken
    url(r'^ride/(?P<ride_id>[0-9]+)/broken/(?P<bike_id>[0-9]+)$', views.report_broken, name='ReportBroken')
]

bikeShare/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from geoposition.fields import GeopositionField


class Status(models.Model):
    """Status of a bike"""
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.description

    class Meta:
        verbose_name_plural = "statuses"


class Station(models.Model):
    """Station class"""
    position = GeopositionField()
    name = models.CharField(max_length=200)
    commissionDate = models.DateTimeField('date commissioned', default=timezone.now)
    capacity = models.IntegerField(default=0)
    status = models.ForeignKey(Status, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return '%s' % self.name


class Bike(models.Model):
    """Bike class"""
    status = models.ForeignKey(Status, on_delete=models.PROTECT, null=True, default=Status.objects.get(description="Available").pk)
    lastRepairDate = models.DateTimeField('date last repaired', null=True)
    commissionDate = models.DateTimeField('date commissioned', default=timezone.now)
    station = models.ForeignKey(Station, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.id.__str__() # + self.status.__str__()


class Ride(models.Model):
    """Ride class connects user wih bike"""
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    bike = models.ForeignKey(Bike, on_delete=models.PROTECT)
    status = models.ForeignKey(Status, on_delete=models.PROTECT, null=True)
    startTime = models.DateTimeField('date time ride start')
    endTime = models.DateTimeField('date time ride end', null=True)
    startStation = models.ForeignKey(Station, on_delete=models.PROTECT, related_name='startStation')
    endStation = models.ForeignKey(Station, on_delete=models.PROTECT, related_name='endStation', null=True)

bikeShare/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    """Form overrides user creation form"""

    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

bikeShare/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.core.serializers import serialize
from django.db.models import F
from django.forms import model_to_dict
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.views import generic

from bikeShare.forms import SignUpForm
from bikeShare.models import Station, Status, Bike, Ride


AVAILABLE_BIKE_STATUS = "Available"
BORROWED_BIKE_STATUS = "Borrowed"


class StationsListView(generic.ListView):
    """View shows all stations that are online"""

    template_name = 'bikeShare/stations.html'
    context_object_name = 'online_station_list'

    def get_queryset(self):
        """Show only online stations"""
        return Station.objects.filter(status=Status.objects.get(description="Online").pk)


class StationBikesListView(generic.DetailView):
    """View shows all bikes that are at a station"""
    template_name = 'bikeShare/stationDetail.html'
    model = Station

    def get_queryset(self):
        """Show bikes available at station"""
        return Station.objects.filter(status=Status.objects.get(description='Online').pk)


@login_required
def bikes_view(request, station_id):
    """View shows all available bikes from a station"""

    station = get_object_or_404(Station, pk=station_id)
    available = Status.objects.get(description=AVAILABLE_BIKE_STATUS)
    bike_set = Bike.objects.filter(station=station.pk, status=available)

    return render(request, 'bikeShare/stationDetail.html', {
        'station': station,
        'bike_set': bike_set})


@login_required
def home_view(request):
    """Returns rides of the current user that are in progress"""

    current_user = request.user
    rides = Ride.objects.filter(user=current_user.pk, status=Status.objects.get(description="In progress").pk)

    return render(request, 'bikeShare/home.html', {
        'rides': rides,
    })


def register(request):
    """View registers a user"""
    if request.method == 'POST':
        # create form
        form = SignUpForm(request.POST)
        # validate form
        if form.is_valid():
            form.save()

            # get data from form
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')

            # create user
            user = authenticate(username=username, password=raw_password)

            # login user
            login(request, user)

            # set welcome message
            messages.add_message(request, messages.INFO, "Welcome to the bike sharing app")
            return redirect('home')
    else:
        # create form
        form = SignUpForm()
    return render(request, 'bikeShare/register.html', {'form': form})


@login_required
def borrow_bike(request, station_id):
    """Method for borrowing a bike"""

    # get the current station
    station = get_object_or_404(Station, pk=station_id)
    try:
        # get the selected bike
        selected_bike = station.bike_set.get(pk=request.POST['bike'])

    # if not found
    except (KeyError, Bike.DoesNotExist):

        # render station detail again, with error message
        return render(request, 'bikeShare/stationDetail.html', {
            'station': station,
            'bike_set': station.bike_set.filter(status=Status.objects.get(description=AVAILABLE_BIKE_STATUS)),
            'error_message': "You didn't select a bike",
        })

    else:

        # change status of bike to borrowed
        borrowed_status = Status.objects.get(description=BORROWED_BIKE_STATUS)
        selected_bike.status = borrowed_status
        selected_bike.station = None
        selected_bike.save()

        # get the current user
        current_user = request.user

        in_progress = Status.objects.get(description="In progress")
        # create a new ride
        ride = Ride(
            user=current_user,
            bike=selected_bike,
            status=in_progress,
            startTime=timezone.now(),
            startStation=station,
        )
        ride.save()

        # set message to inform user
        messages.add_message(request, messages.INFO,
                             "Borrowed bike nr." + selected_bike.id.__str__() + " from " + station.name)
        # redirect to home, to prevent double selection
        return HttpResponseRedirect(reverse('home'))


@login_required
def ride_view(request, ride_id):
    """View displays the selected ride"""

    current_ride = get_object_or_404(Ride, pk=ride_id)
    in_progress = True if current_ride.status == Status.objects.get(description="In progress") else False

    return render(request, 'bikeShare/ride.html', {
        'ride': current_ride,
        'in_progress': in_progress,
    })


@login_required
def finish_ride_select_station(request, ride_id):
    """View displays stations available to place bike at"""

    current_ride = get_object_or_404(Ride, pk=ride_id)
    error = True if current_ride.status != Status.objects.get(description="In progress") else False
    station_list = Station.objects.filter(status=Status.objects.get(description="Online"))

    return render(request, 'bikeShare/finishRide.html', {
        'station_list': station_list,
        'ride': current_ride,
        'error': error,
    })


@login_required
def finish_ride_at_station(request, ride_id, station_id):
    """Method for placing a bike at a station"""

    station = get_object_or_404(Station, pk=station_id)
    ride = get_object_or_404(Ride, pk=ride_id)
    bike = Bike.objects.get(pk=ride.bike.id)

    bike.station = station
    bike.status = Status.objects.get(description=AVAILABLE_BIKE_STATUS)
    bike.save()

    ride.endTime = timezone.now()
    ride.endStation = station
    ride.status = Status.objects.get(description="Finished")
    ride.save()

    # set message to inform user
    messages.add_message(request, messages.INFO,
                         "Returned bike nr." + bike.id.__str__() + " to station " + station.name)

    return HttpResponseRedirect(reverse('home'))


@login_required
def rides_view(request):
    """Show all rides related to a user"""

    # get the current user
    current_user = request.user

    user_rides = Ride.objects.filter(user=current_user)

    return render(request, 'bikeShare/rides.html', {
        'user_rides': user_rides
    })


@login_required
def change_password(request):
    """Change password view"""

    if request.method == "POST":

        # create form
        form = PasswordChangeForm(request.user, request.POST)

        # validate form
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)

            # set message to inform user
            messages.add_message(request, messages.INFO, "Successfully changed password")
            return redirect('home')
        else:

            # set error message
            messages.error(request, "Please correct the errors below")
    else:

        # create form
        form = PasswordChangeForm(request.user)
    return render(request, 'registration/password.html', {
        'form': form
    })


@login_required
def report_broken(request, ride_id, bike_id):
    """Report bike as broken"""

    # get objects
    ride = Ride.objects.get(pk=ride_id)
    bike = Bike.objects.get(pk=bike_id)

    ride.status = Status.objects.get(description="Finished")
    ride.endTime = timezone.now()
    ride.endStation = None
    ride.save()

    bike.status = Status.objects.get(description="Broken")
    bike.station = ride.startStation
    bike.save()

    # set info message for user
    messages.add_message(request, messages.INFO, "Bike nr." + bike.id.__str__() + " reported as broken")

    return HttpResponseRedirect(reverse('home'))

bikeShare/templates/bikeShare/base.html
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>

<style>
    body {
        background-color: #edebac;
    }
</style>

<body>
<nav class="w3-bar w3-green">
    {% if user.is_authenticated %}
        <label class="w3-bar-item w3-left-align">Signed in as {{ user.username }}</label>

        <a class="w3-bar-item w3-button w3-right" href="{% url 'logout' %}">Sign out</a>
        <a class="w3-bar-item w3-button w3-right" href="{% url 'home' %}">Home</a>
    {% endif %}
</nav>
<main>
    {% block content %}
    {% endblock %}
</main>
</body>

bikeShare/templates/bikeShare/finishRide.html
{% extends 'bikeShare/base.html' %}
{% load mathfilters %}

{% block title %}
    Finish ride
{% endblock %}


{% block content %}

    {% if not error %}

        <ul class="w3-ul w3-center">
            <li class="w3-teal">
                <h2>
                    Online stations
                </h2>
            </li>
            {% for station in station_list %}
                <li>
                    {% if station.capacity > station.bike_set.count %}
                        <a href="{% url 'bikeShare:FinishRideAtStation' ride_id=ride.id station_id=station.id %}" class="w3-button w3-block " style="font-weight: bold">{{ station.name }}
                            <p style="font-style: italic">
                                Free spaces: {{ station.capacity|sub:station.bike_set.count }}
                            </p>
                        </a>
                    {% else %}
                        <p class="w3-red" style="font-weight: bold">{{ station.name }}</p>
                        <br>
                        <p style="font-style: italic; font-weight: bold"> Free spaces: 0</p>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>

    {% else %}

        <div class="w3-panel w3-red">
            <h2>Error!</h2>
            <p>Ride is already finished</p>
        </div>

    {% endif %}

{% endblock %}

bikeShare/templates/bikeShare/finishRideAtStation.html
{% extends 'bikeShare/base.html' %}

bikeShare/templates/bikeShare/home.html
{% extends 'bikeShare/base.html' %}

{% block title %}
    Current status of rides
{% endblock %}

{% block content %}
    {% if rides %}
        <ul class="w3-ul w3-center">
            <li class="w3-teal"><h2>Current Rides</h2></li>
            {% for ride in rides %}
                <li>
                    <a class="w3-button w3-block" href="{% url 'bikeShare:RideIndex' ride.id %}">{{ ride.startTime }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <div class="w3-panel w3-teal w3-center">
            <p>No current rides in progress</p>
        </div>
        <div class="w3-center">
            <a class="w3-button w3-red" href="{% url 'bikeShare:Stations' %}">Borrow a bike</a>
        </div>
    {% endif %}
{% endblock %}

bikeShare/templates/bikeShare/register.html
{% extends 'registration/base.html' %}
{% block title %}
    Register
{% endblock %}
{% block content %}
    <div class="w3-card-4">
        <div class="w3-container w3-green">
            <h2>Register</h2>
        </div>
        <form class="w3-form" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="w3-button w3-green" type="submit">Register</button>
            <a class="w3-button w3-red" href="{% url 'home' %}">Cancel</a>
        </form>
    </div>
{% endblock %}

bikeShare/templates/bikeShare/ride.html
{% extends 'bikeShare/base.html' %}

{% block title %}
    Ride {{ ride.id }}
{% endblock %}

{% block content %}
    <ul class="w3-ul ">
        <li class="w3-block">
            <label style="font-weight: bold">User: </label>
            <label >{{ ride.user.first_name }} {{ ride.user.last_name }}</label>
        </li>
        <li class="w3-block">
            <label style="font-weight: bold">Bike: </label>
            <label >{{ ride.bike.id }}</label>
        </li>
        <li class="w3-block">
            <label style="font-weight: bold">Start Time: </label>
            <label >{{ ride.startTime }}</label>
        </li>
        <li>
            <label style="font-weight: bold">End Time: </label>
            {% if not in_progress %}
                <label >{{ ride.endTime }}</label>
            {% else %}
                <label style="font-style: italic; color: #990600;">Ride is currently in progress</label>
            {% endif %}
        </li>
        <li>
            <label style="font-weight: bold">Start Station: </label>
            <label >{{ ride.startStation }}</label>
        </li>
        <li>
            <label style="font-weight: bold">End Station: </label>
            {% if not in_progress %}
                <label >{{ ride.endStation }}</label>
            {% else %}
                <label style="font-style: italic; color: #990600;">Ride is currently in progress</label>
            {% endif %}
        </li>
        <li>
            <label style="font-weight: bold">Status: </label>
            <label >{{ ride.status.description }}</label>
        </li>
    </ul>

    {% if in_progress %}
        <a class="w3-block w3-button w3-center w3-orange" href="{% url 'bikeShare:ReportBroken' ride_id=ride.id bike_id=ride.bike.id %}">Report bike as broken</a>
        <a class="w3-block w3-button w3-center w3-red" href="{% url 'bikeShare:FinishRideSelectStation' ride.id%}">Finish ride</a>
    {% endif %}

{% endblock %}

bikeShare/templates/bikeShare/rides.html
{% extends 'bikeShare/base.html' %}

{% block title %}
    Past rides
{% endblock %}

{% block content %}
    {% if user_rides %}
        <ul class="w3-ul w3-center">
            <li class="w3-teal">
                <h1>Your Past Rides</h1>
            </li>
            {% for ride in user_rides %}
                <li>
                    <a class="w3-button w3-block w3-ripple" style="font-weight: bold" href="{% url 'bikeShare:RideIndex' ride_id=ride.id %}">
                        {{ ride.startStation }} to {{ ride.endStation }}
                        <p style="font-style: italic; color: dodgerblue;" >{{ ride.status }}</p>
                    </a>
                </li>
            {% endfor %}

        </ul>
    {% else %}
        <h2 class="w3-panel w3-block w3-light-green w3-center">You have no past rides</h2>
    {% endif %}

{% endblock %}

bikeShare/templates/bikeShare/stationDetail.html
{% extends 'bikeShare/base.html' %}


{% block title %}
    Online bikes
{% endblock %}

{% block content %}
    <h2 class="w3-block w3-teal w3-center">Bikes available at {{ station.name }} station</h2>
    {% if error_message %}
        <label class="w3-panel w3-red w3-block w3-center w3-large">{{ error_message }}</label>
    {% endif %}
    {% if bike_set %}
        <form class="w3-form w3-center" action="{% url 'bikeShare:Borrow' station.id %}" method="post">
            {% csrf_token %}
            {% for bike in bike_set.all %}
                <input class="w3-radio" type="radio" name="bike" id="bike{{ forloop.counter }}" value="{{ bike.id }}">
                <label for="bike{{ forloop.counter }}">
                    Bike nr. {{ bike.id }}
                </label><br>
            {% endfor %}
            <br>
            <input class="w3-button w3-blue" type="submit" value="Borrow"/>
        </form>
    {% else %}
        <label class="w3-panel w3-yellow w3-block w3-center w3-large">No bikes are available at this station</label>
    {% endif %}
{% endblock %}

bikeShare/templates/bikeShare/stations.html
{% extends 'registration/base.html' %}

{% block title %}
    Online stations
{% endblock %}

{% block content %}
    {% if online_station_list %}
        <ul class="w3-ul w3-center">
            <li class="w3-teal">
                <h1>Online Stations</h1>
            </li>
            {% for station in online_station_list %}
                <li >
                    <a class="w3-button w3-block" style="font-weight: bold" href="{% url 'bikeShare:StationIndex' station_id=station.pk %}">
                        {{ station.name }}<br>
                        <p style="font-style: italic">Bikes available: {{ station.bike_set.count }}</p>
                    </a>

                </li>
            {% endfor %}
        </ul>
    {% else %}
        <label class="w3-panel w3-red">No stations are available</label>
    {% endif %}
{% endblock %}